description: >
  Runs build and test workflow
executor: continuation/default
steps:
  - run:
      name: Create workflow
      environment:
        SCRIPT: <<include(workflows/build_and_test.yml)>>
      command: |
        echo "$SCRIPT" > /tmp/build_and_test.yml
        YARN_LOCK=$(test -f yarn.lock && echo "true" || echo "")
        echo '{"git_tag": "'$CIRCLE_CI_TAG'","pull_request":"'$CIRCLE_PULL_REQUEST'","yarn_lock":"'$YARN_LOCK'"}' > /tmp/build_and_test_parameters.json
  - continuation/continue:
      configuration_path: /tmp/build_and_test.yml
      parameters: /tmp/build_and_test_parameters.json
