description: >
  Runs build and test workflow
executor: continuation/default
parameters:
  git_tag:
    type: string
    default: ''
steps:
  - run:
      name: Create workflow
      environment:
        SCRIPT: <<include(workflows/build_and_test.yml)>>
      command: |
        echo "$SCRIPT" > /tmp/build_and_test.yml
  - continuation/continue:
      configuration_path: /tmp/build_and_test.yml
      parameters: '{"git_tag": "<< parameters.git_tag >>"}'
